### ISSUE TITLE
Finetune and handle scoring

### ISSUE THREAD

**Issue by DomMcOyle** [GiovanniPioDelvecchio/NLP-Project#4]
scoring of the models must be done on basis of F1 score/precision/recall macro on the test and validation splits. 
Probably it will be useful to tune a threshold for discretization of labels if the model produces a different
probablility for each class.

**Comment by DomMcOyle** [comment]
Tests should be produced also on the multicultural split.

**Comment by GiovanniPioDelvecchio** [comment]
It is necessary to build a custom F1 function in order to obtain scores.

**Comment by DomMcOyle** [comment]
Custom function for producing results (both macro-aggregation and per-class) was implemented. Closing this issue.
