### ISSUE TITLE
Creation of a BERT-like baseline

### ISSUE THREAD

**Issue by GiovanniPioDelvecchio** [GiovanniPioDelvecchio/NLP-Project#5]
It is necessary to extend the baseline by adding a language model at its base, in particular one can choose between the following transformer-based language models:
- BERT (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/bert)
- ALBERT (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/albert)
- BERT (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/bert)
- BORT (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/bort)
- ConvBERT (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/convbert)
- ELECTRA (really suggested, try it out I'm curious) (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/electra)
- DistilBERT (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/distilbert)
- FNET (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/fnet)
- Funnel Transformer (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/funnel)
- MPNet (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/mpnet)
- REFORMER (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/reformer)
- SqueezeBert (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/squeezebert)
- YOSO (https://huggingface.co/docs/transformers/v4.26.0/en/model_doc/yoso)

**Comment by DomMcOyle** [comment]
paper mentioned in the dataset one. Allows learning rules capturing relations between labels:
https://link.springer.com/article/10.1007/s10994-016-5552-1

**Comment by DomMcOyle** [comment]
the more suitable models for testing are:
ELECTRA
ConvBERT
BORT
Funnel Transformers
the others could f**k themselves

**Comment by DomMcOyle** [comment]
BORT tested with the same head, gave 0.24 F1
i think it can be discarded

**Comment by DomMcOyle** [comment]
Funnel gave 0.3765 F1
but probably it compresses the model too much. Probably one could try to finetune it directly.
